"""car table

Revision ID: 0ce8f14471b1
Revises: 
Create Date: 2020-08-12 09:03:27.379891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce8f14471b1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carname', sa.String(length=32), nullable=True),
    sa.Column('carhp', sa.String(length=16), nullable=True),
    sa.Column('cartorque', sa.String(length=16), nullable=True),
    sa.Column('cardescription', sa.String(length=128), nullable=True),
    sa.Column('carprice', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_cardescription'), 'car', ['cardescription'], unique=True)
    op.create_index(op.f('ix_car_carhp'), 'car', ['carhp'], unique=True)
    op.create_index(op.f('ix_car_carname'), 'car', ['carname'], unique=True)
    op.create_index(op.f('ix_car_carprice'), 'car', ['carprice'], unique=True)
    op.create_index(op.f('ix_car_cartorque'), 'car', ['cartorque'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_cartorque'), table_name='car')
    op.drop_index(op.f('ix_car_carprice'), table_name='car')
    op.drop_index(op.f('ix_car_carname'), table_name='car')
    op.drop_index(op.f('ix_car_carhp'), table_name='car')
    op.drop_index(op.f('ix_car_cardescription'), table_name='car')
    op.drop_table('car')
    # ### end Alembic commands ###
