"""fixing unique values

Revision ID: 448f1e718afc
Revises: d1ab4ca7443f
Create Date: 2020-08-12 09:15:01.695569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448f1e718afc'
down_revision = 'd1ab4ca7443f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_car_cardescription', table_name='car')
    op.create_index(op.f('ix_car_cardescription'), 'car', ['cardescription'], unique=False)
    op.drop_index('ix_car_carhp', table_name='car')
    op.create_index(op.f('ix_car_carhp'), 'car', ['carhp'], unique=False)
    op.drop_index('ix_car_carprice', table_name='car')
    op.create_index(op.f('ix_car_carprice'), 'car', ['carprice'], unique=False)
    op.drop_index('ix_car_cartorque', table_name='car')
    op.create_index(op.f('ix_car_cartorque'), 'car', ['cartorque'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_cartorque'), table_name='car')
    op.create_index('ix_car_cartorque', 'car', ['cartorque'], unique=1)
    op.drop_index(op.f('ix_car_carprice'), table_name='car')
    op.create_index('ix_car_carprice', 'car', ['carprice'], unique=1)
    op.drop_index(op.f('ix_car_carhp'), table_name='car')
    op.create_index('ix_car_carhp', 'car', ['carhp'], unique=1)
    op.drop_index(op.f('ix_car_cardescription'), table_name='car')
    op.create_index('ix_car_cardescription', 'car', ['cardescription'], unique=1)
    # ### end Alembic commands ###
