"""car brand

Revision ID: 945cf08b9ec1
Revises: 448f1e718afc
Create Date: 2020-08-14 23:00:22.354361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945cf08b9ec1'
down_revision = '448f1e718afc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('carbrand', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_car_carbrand'), 'car', ['carbrand'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_carbrand'), table_name='car')
    op.drop_column('car', 'carbrand')
    # ### end Alembic commands ###
