"""car image

Revision ID: bbab8b637523
Revises: 945cf08b9ec1
Create Date: 2020-08-17 08:51:26.923300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbab8b637523'
down_revision = '945cf08b9ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('carimage', sa.String(length=528), nullable=True))
    op.create_index(op.f('ix_car_carimage'), 'car', ['carimage'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_carimage'), table_name='car')
    op.drop_column('car', 'carimage')
    # ### end Alembic commands ###
